### ISSUE TITLE
Настройка WARP

### ISSUE THREAD

**Issue by pvolkov** [Nidelon/ru-block-v2ray-rules#1]
Привет!
Можешь, пожалуйста, поделиться настройкой WARP для этих списков? 

Я сделал следующее, но не завелось:
1. Установил WARP+ WireProxy через меню настроек 3x-ui `x-ui`
2. Настроил WARP+. Сервер запущен на 127.0.0.1:40000
3. Скачал твои файлы
4. Добавил в настройках XRay 3x-ui:
```
 {
    "tag": "WARP",
    "protocol": "socks",
    "settings": {
      "servers": [
        {
          "address": "127.0.0.1",
          "port": 40000
        }
      ]
    }
  }
```
5. В настройках маршрутизации добавил:
```
  {
    "type": "field",
    "outboundTag": "WARP",
    "domain": [
      "ext:geosite_RU.dat:ru-block"
    ],
    "ip": [
      "ext:geoip_RU.dat:ru-block"
    ]
  }
```
6. Сохранил, проверил, не работает.

Надо ли включать в настройках XRay пункты про прямое подключение к доменам и IP в России?
Надо ли осуществлять дополнительные настройки на клиенте?

Спасибо!

**Comment by Nidelon** [comment]
Так, давай по порядку.
1. Убедится что прокси WARP работает.
1. Проверь, есть ли файлы `geoip_RU.dat` и `geosite_RU.dat` при помощи команды `ls /usr/local/x-ui/bin`
2. Совпадают ли следующие настройки:
![image](https://github.com/Nidelon/ru-block-v2ray-rules/assets/48694850/854734b6-14ec-4496-a631-a262331307f5)
![image](https://github.com/Nidelon/ru-block-v2ray-rules/assets/48694850/2736cb61-3bda-4c68-9671-052c57513e8c)
Настройка правил маршрутизации:
```
[
  {
    "type": "field",
    "inboundTag": [
      "api"
    ],
    "outboundTag": "api"
  },
  {
    "type": "field",
    "outboundTag": "WARP",
    "domain": [
      "ext:geosite_RU.dat:ru-block"
    ],
    "ip": [
      "ext:geoip_RU.dat:ru-block"
    ]
  }
]
```
![image](https://github.com/Nidelon/ru-block-v2ray-rules/assets/48694850/3dabcc83-731d-433a-8c9c-d8a842683c6d)
Конфигурация исходящих:
```
{
    "protocol": "freedom",
    "settings": {}
  },
  {
    "tag": "blocked",
    "protocol": "blackhole",
    "settings": {}
  },
  {
    "tag": "WARP",
    "protocol": "socks",
    "settings": {
      "servers": [
        {
          "address": "127.0.0.1",
          "port": 40000
        }
      ]
    }
  }
]
```
3. После применений настроек, обязательно перезапустить панель.

Также на всякий предупрежу, это нужно для того, что бы удобно иметь vpn сервер в России с возможностью подключаться к заблокированным сайтам. Довольно специфичная задача.

**Comment by Nidelon** [comment]
Ну и держи для удобства настроенный конфиг.
[config.json](https://github.com/Nidelon/ru-block-v2ray-rules/files/13453079/config.json)

**Comment by pvolkov** [comment]
Тысячу раз всё проверял и не заметил, что в маршрутизации доменов было не IPIfNonMatch. Теперь всё заработало! Спасибо огромное!

**Comment by Nidelon** [comment]
Хорошо, тогда добавлю замечание в README насчёт этой строки.

**Comment by pvolkov** [comment]
Ещё вопрос. Как ты решил проблему с доступом к сайтам, например, avito.ru или pochta.ru, которые блокируют доступ при активном VPN подключении? На клиенте с `domain:ru` работает, но хочется более универсального решения. Пробовал много вариантов различных правил маршрутизации, но ни одно не сработало.

Пользуюсь VPS от TimeWeb, ЦОД в Санкт-Петербурге.

**Comment by Nidelon** [comment]
> Ещё вопрос. Как ты решил проблему с доступом к сайтам, например, avito.ru или pochta.ru, которые блокируют доступ при активном VPN подключении? На клиенте с правилом для direct `domain:ru` работает, но хочется более универсального решения. Пробовал много вариантов различных правил маршрутизации, но ни одно не сработало.
> 
> Пользуюсь VPS от TimeWeb, ЦОД в Санкт-Петербурге.

Странно, у меня такие проблемы отсутствуют, сервер точно не пропускает весь трафик через WARP? Проверь какой IP адрес, забугорный или российский при включенном VPN, он должен быть на незаблокированных сайтах Российским.

**Comment by pvolkov** [comment]
> > Ещё вопрос. Как ты решил проблему с доступом к сайтам, например, avito.ru или pochta.ru, которые блокируют доступ при активном VPN подключении? На клиенте с правилом для direct `domain:ru` работает, но хочется более универсального решения. Пробовал много вариантов различных правил маршрутизации, но ни одно не сработало.
> > Пользуюсь VPS от TimeWeb, ЦОД в Санкт-Петербурге.
> 
> Странно, у меня такие проблемы отсутствуют, сервер точно не пропускает весь трафик через WARP? Проверь какой IP адрес, забугорный или российский при включенном VPN, он должен быть на незаблокированных сайтах Российским.

При подключенном VPN IP адрес российский и совпадает с тем, что предоставляет TimeWeb. Скажи, пожалуйста, а у какого провайдера ты развернул свой VPS? Попробую у него же создать сервер.

**Comment by Nidelon** [comment]
> > > Ещё вопрос. Как ты решил проблему с доступом к сайтам, например, avito.ru или pochta.ru, которые блокируют доступ при активном VPN подключении? На клиенте с правилом для direct `domain:ru` работает, но хочется более универсального решения. Пробовал много вариантов различных правил маршрутизации, но ни одно не сработало.
> > > Пользуюсь VPS от TimeWeb, ЦОД в Санкт-Петербурге.
> > 
> > 
> > Странно, у меня такие проблемы отсутствуют, сервер точно не пропускает весь трафик через WARP? Проверь какой IP адрес, забугорный или российский при включенном VPN, он должен быть на незаблокированных сайтах Российским.
> 
> При подключенном VPN IP адрес российский и совпадает с тем, что предоставляет TimeWeb. Скажи, пожалуйста, а у какого провайдера ты развернул свой VPS? Попробую у него же создать сервер.

Тот же что и у вас. Хочу помочь, но тут я не знаю почему у вас блокируются сайты, они никак ругаться не должны.

**Comment by pvolkov** [comment]
> > > > Ещё вопрос. Как ты решил проблему с доступом к сайтам, например, avito.ru или pochta.ru, которые блокируют доступ при активном VPN подключении? На клиенте с правилом для direct `domain:ru` работает, но хочется более универсального решения. Пробовал много вариантов различных правил маршрутизации, но ни одно не сработало.
> > > > Пользуюсь VPS от TimeWeb, ЦОД в Санкт-Петербурге.
> > > 
> > > 
> > > Странно, у меня такие проблемы отсутствуют, сервер точно не пропускает весь трафик через WARP? Проверь какой IP адрес, забугорный или российский при включенном VPN, он должен быть на незаблокированных сайтах Российским.
> > 
> > 
> > При подключенном VPN IP адрес российский и совпадает с тем, что предоставляет TimeWeb. Скажи, пожалуйста, а у какого провайдера ты развернул свой VPS? Попробую у него же создать сервер.
> 
> Тот же что и у вас. Хочу помочь, но тут я не знаю почему у вас блокируются сайты, они никак ругаться не должны.

Опытным путём выяснил, что из трёх доступных ЦОДов у Timeweb, всё работает как надо только на SPB-2. Это странно, но работает)
