### ISSUE TITLE
List usage

### ISSUE THREAD

**Issue by aleskxyz** [Nidelon/ru-block-v2ray-rules#3]
Hi,

I'm trying to generate some bypass and block rules for sing-box. From my understanding, the list that you have created includes websites that are blocked in Russia. If we want to use it, we need to send traffic to those websites through a VPN and bypass the rest of the traffic.
Is that correct?
Is that list accurate and updated regularly?

**Comment by Nidelon** [comment]
Hello, yes, that’s right, the list includes addresses blocked in Russia by the RKN.
Data is updated daily based on the list from https://antifilter.download/
And you shouldn’t worry about the reliability of the list, I used it myself, and there were no mistakes with blocked sites, and from the site’s FAQ you can find out that they take the database directly from the RKN.

**Comment by Nidelon** [comment]
Can I help with anything else, or can I close the issue?
