### ISSUE TITLE
Роутер крашится после запуска правил

### ISSUE THREAD

**Issue by Greatbar** [Nidelon/ru-block-v2ray-rules#4]
Роутер перестает отвечать после запуска правил. Xiaomi Redmi Router AX6S на OpenWrt 23.05.4 .
Попробовал сделать через X3-ui и WARP,  но не разобрался почему трафик ни в какую не хочет идти через него на виртуальном сервере. Сам используюсь VLESS + Reality

**Comment by Nidelon** [comment]
Я его уже как давно перестал использовать, тут список для примера и если кому понадобится. По зависанию роутера тут совсем не знаю, может не выдерживает кол-во сайтов? По x3-ui вполне возможно WARP не может запуститься, только у некоторых провайдеров он проходит (См. #1 ). Сейчас попытаюсь накатить на домашний сервер, может инструкцию поменяю если заработает.

**Comment by Nidelon** [comment]
По роутеру ничего не могу порекомендовать, потому что у меня на Mi Router 4A Gigabit Edition v2 не влезет список никоим образом, так что не могу проверить.

**Comment by Nidelon** [comment]
Да, WARP никак не подключается, чуть позже подчищу инструкцию и оставлю просто как GeoSite и GeoIp.

**Comment by Nidelon** [comment]
Закрываю issue за неимением ответа.
