### ISSUE TITLE
Объединение с v2ray/domain-list-community

### ISSUE THREAD

**Issue by PentiumB** [Nidelon/ru-block-v2ray-rules#5]
Не рассматриваете возможность добавить категорию Ru-block в основную базу сообщества v2ray? Думаю это было бы очень удобно.
https://github.com/v2ray/domain-list-community/pulls

**Comment by Nidelon** [comment]
Уже существует форк https://github.com/jameszeroX/zkeen-domains для списка доменов и https://github.com/jameszeroX/zkeen-ip для списка IP адресов.

**Comment by Nidelon** [comment]
Глянул, для какого то zkeen-а, но не вижу различия в этих файлах, та основная база domain list community обновляется с огромными промежутками, что немного не подходит под наш реестр. Сделать pull request тоже не могу, так как придётся удалять другой конфликтующий репозиторий у меня, что полностью сломает генерацию новых файлов здесь.

**Comment by PentiumB** [comment]
Ок спасибо за ответ. Я сейчас закинул оба файла в папку bin(где хранятся основные geoip и geosite) клиента V2RayN, создал правило на основе blacklist, пытаюсь эти файлы вызвать и происходит то, что я не понимаю. Если я их вызываю в формате "ruip.dat:ru-block" весь трафик гуляет через direct независимо от того куда я захожу, ежели вызываю "ext:ruip.dat:ru-block" весь трафик гуляет через proxy. Если я вдруг пытаюсь заменить основные файлы вашими, ложится весь клиент. Правило рабочее проверял вписывая конкретный домен. 
![image](https://github.com/user-attachments/assets/57bb01b8-a5ab-4302-aa0a-431934fb2ff5)

**Comment by Nidelon** [comment]
Основные лучше не менять, так как могут использоваться самим клиентом. IP адреса не думаю что хорошая идея пихать в домены. Также лучше убедиться, маршрутизирует ли он по приоритету по правилам списка и правильно ли перенаправляет трафик. С V2RayN не работал, только xray щупал, позже гляну как будет свободное время.

**Comment by PentiumB** [comment]
> IP адреса не думаю что хорошая идея пихать в домены
Использую такую-же схему на обратном правиле с основными файлами, для обхода ру сегмента, все ок.
Толи я как-то не правильно файлы закидываю или вызываю, толи V2RayN с ними работать не очень хочет.
![image](https://github.com/user-attachments/assets/f1c89e01-07c7-45a0-b0e6-d371ab435309)

**Comment by Nidelon** [comment]
Ну или можно так проксировать, так даже легковеснее будет :D

**Comment by Nidelon** [comment]
Можно и так, даже легковеснее будет :D, хотя и будет проксировать всё и вся не из России. Точно к сожалению не могу понять без прям полной картины перед собой, хотя могу последнее подсказать, в доменной стратегии поменять на IPIfNonMatch потому что у человека точно такая же проблема была #1
